#!/bin/bash
set -e

# Install DDclient if necessary
sudo apt install -y ddclient

while true
do
    read -p "Enter your changeip.com Email OR Username: " LOGIN
    read -p "Enter your changeip.com password: " PASSWORD
    read -p "Enter your domain: " DOMAIN
    echo "Your changeip.com Email OR Username is: $LOGIN"
    echo "Your changeip.com password is: $PASSWORD"
    echo "Your domain (e.g. subdomain.dynamic-dns.net) : $DOMAIN"
    while true
    do
        read -p "Is this correct (y/n)?: " answer
        case $answer in
            [yY]* ) break 2;;
            [nN]* ) break 1;;
            * ) ;;
        esac
    done
done
read -n 1 -s -r -p "Press any key to continue"

TEMP=$(mktemp)
cat <<CONFIG_DDCLIENT > ${TEMP}
# Configuration file for ddclient generated by debconf
#
# /etc/ddclient.conf

    daemon=3600
    use=web, web=ip.changeip.com
    protocol=changeip
    ssl=yes
    server=nic.changeip.com/nic/update
    login=${LOGIN}
    password='${PASSWORD}'
    ${DOMAIN}
CONFIG_DDCLIENT
sudo cp --no-preserve=mode,ownership ${TEMP} /etc/ddclient.conf